<template><div><p>使用萤石开放平台的 <code v-pre>ezopen JS SDK</code> 接入 web 页面的监控视频时，代码打包后部署到服务器上出现这个 <code v-pre>DOMException: Failed to construct 'Worker'...</code> 错误。</p>
<!-- more -->
<h2 id="web-worker-跨源访问问题" tabindex="-1"><a class="header-anchor" href="#web-worker-跨源访问问题" aria-hidden="true">#</a> Web Worker 跨源访问问题</h2>
<figure><img src="https://cdn.jsdelivr.net/gh/wardendon/wiki-image@main/img/202401082104545.png" alt="cannot be accessed from origin '..'" tabindex="0" loading="lazy"><figcaption>cannot be accessed from origin '..'</figcaption></figure>
<p><a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Spawning_a_worker" target="_blank" rel="noopener noreferrer">Mozilla 文档说<ExternalLinkIcon/></a>，Web Worker 必须遵守同源策略，并使用 CORS 来允许跨源访问。</p>
<p>我实际测试的结果是：使用域名 + https 协议访问部署的网站没有问题，萤石的视频流正常获取，但是使用 ip 地址访问就出现上面的错误。</p>
<p>让甲方提供域名，甲方不愿意，说就只用 ip 访问网站。</p>
<p>好吧，查询文档，UIKit 的<a href="https://open.ys7.com/doc/zh/uikit/uikit_javascript.html" target="_blank" rel="noopener noreferrer">旧版文档<ExternalLinkIcon/></a>里的监控模式配置说明里提到一个<code v-pre>decoderPath</code>属性，填写解码器绝对路径，就是说部署的时候要把 ezuikit 的源码放入服务器，然后将文件路径作为属性值，那么调用的时候就 是同源的了。</p>
<p>但是我开发时 是按照<a href="https://open.ys7.com/help/1772" target="_blank" rel="noopener noreferrer">新版文档<ExternalLinkIcon/></a>开发的，文档里的初始化参数说明里根本没有<code v-pre>decoderPath</code>字段，也没有类似含义的字段，node_modules 里找源码搜索也搜不到这个变量。</p>
<p>最终在 EZUIKit-JavaScript-npm 的 github 仓库里找到了<a href="https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/blob/master/demos/base-demo/localDecoder.html" target="_blank" rel="noopener noreferrer">本地解码库示例<ExternalLinkIcon/></a>。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> playr<span class="token punctuation">;</span>
<span class="token function">fetch</span><span class="token punctuation">(</span><span class="token string">"https://open.ys7.com/jssdk/ezopen/demo/token"</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">response</span><span class="token punctuation">)</span> <span class="token operator">=></span> response<span class="token punctuation">.</span><span class="token function">json</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
  <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">res</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> accessToken <span class="token operator">=</span> res<span class="token punctuation">.</span>data<span class="token punctuation">.</span>accessToken<span class="token punctuation">;</span>
    playr <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EZUIKit<span class="token punctuation">.</span>EZUIKitPlayer</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token literal-property property">id</span><span class="token operator">:</span> <span class="token string">"video-container"</span><span class="token punctuation">,</span> <span class="token comment">// 视频容器ID</span>
      <span class="token literal-property property">accessToken</span><span class="token operator">:</span> accessToken<span class="token punctuation">,</span>
      <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token string">"ezopen://open.ys7.com/G39444019/1.live"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">template</span><span class="token operator">:</span> <span class="token string">"simple"</span><span class="token punctuation">,</span> <span class="token comment">// simple - 极简版;standard-标准版;security - 安防版(预览回放);voice-语音版; theme-可配置主题；</span>
      <span class="token literal-property property">plugin</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"talk"</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token comment">// 加载插件，talk-对讲</span>
      <span class="token literal-property property">staticPath</span><span class="token operator">:</span> <span class="token string">"/ezuikit_static/v65"</span><span class="token punctuation">,</span>
      <span class="token literal-property property">width</span><span class="token operator">:</span> <span class="token number">600</span><span class="token punctuation">,</span>
      <span class="token literal-property property">height</span><span class="token operator">:</span> <span class="token number">400</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>也就是说字段名称变成了<code v-pre>staticPath</code>...😅😅😅，<strong>要把这个 demo 的 ezuikit_static 文件夹复制到服务器上，然后在 staticPath 里填链接，指定一个版本</strong>，比如 v65。</p>
<p>我选择放入项目的 public 文件夹里然后配置 vite 的环境变量读取，最终解决了这个问题。</p>
<h2 id="打包运行异常" tabindex="-1"><a class="header-anchor" href="#打包运行异常" aria-hidden="true">#</a> 打包运行异常</h2>
<p>还有一个坑就是 <code v-pre>vite</code> 使用 <code v-pre>terser</code> 方式打包后萤石视频组件无法使用，提示 <code v-pre>xe.log is not a function</code>，改用<code v-pre>esbuild</code> 方式打包后页面正常。</p>
<h2 id="最佳实践" tabindex="-1"><a class="header-anchor" href="#最佳实践" aria-hidden="true">#</a> 最佳实践</h2>
<p>最后附上我的 vue + EZUIKit 的最佳实践。</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">pnpm</span> <span class="token function">add</span> ezuikit-js
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><div class="language-vue line-numbers-mode" data-ext="vue"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>template</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>video-container<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>video<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>template</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ts<span class="token punctuation">"</span></span> <span class="token attr-name">setup</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
<span class="token keyword">import</span> EZUIKit <span class="token keyword">from</span> <span class="token string">"ezuikit-js"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> useUserStore <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@/stores/modules/user"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> userStore <span class="token operator">=</span> <span class="token function">useUserStore</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">let</span> <span class="token literal-property property">player</span><span class="token operator">:</span> any <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">;</span>

<span class="token function">onMounted</span><span class="token punctuation">(</span><span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> aToken <span class="token operator">=</span> <span class="token keyword">await</span> userStore<span class="token punctuation">.</span>getYsToken<span class="token punctuation">;</span>
  player <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EZUIKit<span class="token punctuation">.</span>EZUIKitPlayer</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">id</span><span class="token operator">:</span> <span class="token string">"video-container"</span><span class="token punctuation">,</span> <span class="token comment">// 视频容器ID</span>
    <span class="token literal-property property">template</span><span class="token operator">:</span> <span class="token string">"pcLive"</span><span class="token punctuation">,</span>
    <span class="token literal-property property">width</span><span class="token operator">:</span> <span class="token number">380</span><span class="token punctuation">,</span>
    <span class="token literal-property property">height</span><span class="token operator">:</span> <span class="token number">230</span><span class="token punctuation">,</span>
    <span class="token literal-property property">accessToken</span><span class="token operator">:</span> aToken<span class="token punctuation">,</span>
    <span class="token literal-property property">staticPath</span><span class="token operator">:</span> <span class="token constant">EZUIKIY_STATIC_PATH</span><span class="token punctuation">,</span>
    <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">ezopen://open.ys7.com/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>设备序列号<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/1.hd.live</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
    <span class="token function-variable function">handleError</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">err</span><span class="token operator">:</span> Error</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"获取直播流错误 :>> "</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token function">onBeforeUnmount</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  player<span class="token punctuation">.</span><span class="token function">stop</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token doc-comment comment">/** 切换视频地址 */</span>
<span class="token keyword">const</span> <span class="token function-variable function">handleClick</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">xlh</span><span class="token operator">:</span> string</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  player<span class="token punctuation">.</span><span class="token function">stop</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 执行stop方法停止上次取流</span>
  <span class="token comment">// 切换播放地址场景</span>
  player<span class="token punctuation">.</span><span class="token function">play</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">url</span><span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">ezopen://open.ys7.com/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>xlh<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/1.hd.live</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>荧石的每个 token 具备独立的 7 天生命周期，不要频繁调用避免占用过多接口调用次数，所以讲它存到本地，到期后重新请求。</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// src/store/modules/user.ts</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> defineStore <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"pinia"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> piniaPersistConfig <span class="token keyword">from</span> <span class="token string">"@/stores/helper/persist"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">const</span> useUserStore <span class="token operator">=</span> <span class="token function">defineStore</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  id<span class="token operator">:</span> <span class="token string">"user-store"</span><span class="token punctuation">,</span>
  <span class="token function-variable function">state</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span><span class="token punctuation">{</span> ysToken<span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">,</span> ysExpireTime<span class="token operator">:</span> <span class="token number">0</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
  getters<span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token comment">// 获取荧石 AccessToken</span>
    <span class="token keyword">async</span> <span class="token function">getYsToken</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span><span class="token builtin">string</span><span class="token operator">></span> <span class="token punctuation">{</span>
      <span class="token comment">// 如果已经有了，根据时间戳判断是否过期</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>ysToken <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>ysExpireTime <span class="token operator">></span> Date<span class="token punctuation">.</span><span class="token function">now</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>ysToken<span class="token punctuation">;</span>
      <span class="token comment">// 如果没有，就去请求</span>
      <span class="token keyword">const</span> <span class="token punctuation">{</span> data <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">getYsAccessToken</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>ysToken <span class="token operator">=</span> data<span class="token punctuation">.</span>accessToken<span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>ysExpireTime <span class="token operator">=</span> data<span class="token punctuation">.</span>expireTime<span class="token punctuation">;</span>
      <span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>ysToken<span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  persist<span class="token operator">:</span> <span class="token function">piniaPersistConfig</span><span class="token punctuation">(</span><span class="token string">"user-store"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果不想使用 EZUIKitPlayer 里提供的几种默认的模版，那么就删掉 <code v-pre>template</code>，改用 <code v-pre>themeData</code>，参考<a href="https://github.com/Ezviz-OpenBiz/EZUIKit-JavaScript-npm/blob/master/demos/base-demo/themeData.html" target="_blank" rel="noopener noreferrer">自定义主题 demo<ExternalLinkIcon/></a></p>
</div></template>


